### ISSUE TITLE
当 WordPress地址 和 站点地址 不相同时 Pony.moc 路径会错

### ISSUE THREAD

**Issue by zanjie1999** [juzeon/wp-3d-pony#1]
当 WordPress地址 和 站点地址 不相同时 
Pony.moc 的路径是基于 站点地址 而不是 WordPress地址
导致路径错误

**Comment by juzeon** [comment]
会尝试修复。
目前锅太多了还有eqcn的app在写=。=

**Comment by zanjie1999** [comment]
看好你喔

**Comment by zanjie1999** [comment]
翻了下官方文档,改了一下,问题解决

/wp-3d-pony/wp-3d-pony.php
第14行
```$this->assetUrl=substr(wp_upload_dir()['baseurl'], strlen(home_url().'/')).'/wp-3d-pony/';```

**Comment by juzeon** [comment]
直接发个pull request吧w

**Comment by zanjie1999** [comment]
已发w

**Comment by juzeon** [comment]
Fixed.
